### ISSUE TITLE
MM bots doesn't save bots power picks

### ISSUE THREAD

**Issue by linkztream** [ImaginaryDevelopment/imaginary-hero-designer#23]
When I re-open my mastermind build that I created in the same version yesterday,  the pet powers Battle Drones, Protector Bots and Assault bot are now empty power levels and I need to repick the powers for level 1, 12 and 26 respectively.

Steps to reproduce:

- Create Bots/time Mastermind, Natural Origin
- Pick power and slots (I 6-slotted the pets)
- Save file, I used a custom path "C:\Users\plm\Dropbox (Personal)\Spel\CoH\Builds\Mastermind\System Override - Mastermind (Robotics).mxd"
- Re-open the file, slots are assigned at level 1,12, 26 but no powers or enhancements. All the other powers, slots and enhancements are fine.

| Copy & Paste this data into Mids' Hero Designer to view the build |
|-------------------------------------------------------------------|
|MxDz;1394;634;1268;HEX;|
|78DA6593C96ED3501486EFF5D090A421CE44DBCC43434B4343AC963512E3A68188B|
|0AF4CE3B6969C38CA80E8923D0B7801A60D62166C1884847807508B98B64C05DE20|
|1CEE394A2DD952CFE7FEF7CCF1AD5F3E39F9F8CC95638C6B276CA3DF5FAD1BFD81D|
|96B5B9D96EFAC3118F60C9BC1136E6E81DCCE9FBB64F67A56CBF48196DC735D6D0E|
|DB6DA7533DEF5C7406D65ABFE03A3A3E5C5FAF5EB0DA26A4EE58DDA16D0C2CA7C38|
|20DC7B1ABA76D6B63731010EFCDAE69B6C2E275C5345A66AFBF697543E8F6DFCBEA|
|6C444F75AD35F8CFB45BD4E8D634745286BF113CAAB04C7259C5652784DD4E307A4|
|6327BC419D31536F104B9F094F80CB903BE1C7D55BE2B0B6DDF2F64E01B32FE1D99|
|FF812CFC447E805899EAC82F248C7D8E2CBD42CEBE44BE561953D197A90526B420E|
|CD8C751F389CE8BA0F851E1FE0A7A058862FCA0709B74D9FD2EAB091B8524214A1B|
|A25231D0C2A829E11BD892761319BD4DBC838CDF427E84F122D8B212B90BC11918F|
|D1EF13EAEAFF490F800F9096262B492D87B49F8CEEE10B79173EF9011E82941F913|
|098C3FA01163C8E938318A7C033B9CA2354E8969C55A66C46BD265D32E9B15F633D|
|44AD10A52542E4BE5B211649ECAE6A96C095ACCD02A337E5CCB5B6821472DE468BD|
|5F207791C62E72598C775822CA4415F9157CCB98532DA7F14B3A9821668979E45C8|
|198433634C6E66986F91AF6786889B84C3C4A5FB88EE43043057BE315B189456165|
|D0AB94AB3A833FEB912431454C23F50C5281981AC64835DAA14E3BD4696769657CF|
|BF0CEB2058F52F328BA4759F228CB1E65C5A3D4F794514319DF6DC6C5A95F1BDFD8|
|D16E004EB9FBF48F47F9ED51FE06C639257E15BF88C5EBC46BC87FA2F83D41|
|-------------------------------------------------------------------|

**Comment by Pine-CoH** [comment]
For some reason, when reading back that binary string, it is reading a -1 as the nid's for all three pet summon powers. Not sure what to make of it. Only seem to be getting it from this import chunk. I can open the my other MM files just fine.

**Comment by Metalios** [comment]
The same thing happened with MM Kinetics and Radiation trees prior to the database update I just pushed, and those were related to index errors. This could possibly be related but would have to investigate.

**Comment by ImaginaryDevelopment** [comment]
This looks like a problem with an older version, it isn't happening with 2.6. I tried with a new build, and then with the above failing import. The import still fails, but if I add the powers and enhancements in, it works just fine with a new save. I tried sticking at least 1 enh in each of the lost pet powers, one SET IO, one Invention IO, and one SO. nothing was lost on reload.
