### ISSUE TITLE
Sentinel Refractor Beam is still disappearing.

### ISSUE THREAD

**Issue by SunsetteSkye** [ImaginaryDevelopment/imaginary-hero-designer#61]
App Name: Mids Reborn
App Version: 2.6.0.2
Bug to Report: on my BR/EA Sentinel Refractor Beam got saved somehow as the unslottable proc power Sandman: Chance to Heal Self. I used no IOs from this set. Tried on both my old build from before and the newest.

**Comment by Metalios** [comment]
This issue was the result of a database indexing issue, this should be resolved as the index for Sentinel's Refractor Beam was changed to the appropriate index. You may have to remake the build as the old build file is probably referencing the incorrect index.

**Comment by SunsetteSkye** [comment]
Nope, still an issue. Here's a video.

https://i.imgur.com/dAaZ9TA.gifv
